CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR(250) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(250) NOT NULL
);

INSERT INTO USERS (username, password) VALUES ('username', '$2a$10$GiseHkdvwOFr7A9KRWbeiOmg/PYPhWVjdm42puLfOzR/gIAQrsAGy');
